version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - .docker/db-setup.sh:/docker-entrypoint-initdb.d/setup.sh

  app:
    build: .
    working_dir: /app
    entrypoint: ["sh", "-c"]
    command: ["bundle install && bundle exec puma"]
    environment:
      BUNDLE_PATH: /bundle_cache
      ENV_FILE: .env.development
    depends_on:
      - db
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - cache-volume:/bundle_cache

volumes:
  cache-volume:
