name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Rubocop & RSpec
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install bundler
        run: gem install bundler
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Setup the database
        run: |
          psql -v ON_ERROR_STOP=1 postgres://postgres:postgres@0.0.0.0:5432 <<-EOSQL
              CREATE ROLE app WITH LOGIN PASSWORD 'postgres';
              CREATE ROLE app_password WITH LOGIN PASSWORD 'postgres';
              CREATE DATABASE app_test OWNER app;
          EOSQL
      - name: Migrate the database
        run: |
          DATABASE_URL=postgres://postgres:postgres@0.0.0.0:5432/app_test bundle exec rake migrate[1]
          bundle exec rake migrate[2]
          DATABASE_URL=postgres://app_password:postgres@0.0.0.0:5432/app_test bundle exec rake migrate[3]
          bundle exec rake migrate
      - name: Run Rspec
        run: bundle exec rspec
env:
  DATABASE_URL: postgres://app:postgres@0.0.0.0:5432/app_test
  HMAC_SECRET: 0439b262109093e2354fcf90c7367b65
  RACK_ENV: test
