# frozen_string_literal: true

class Account < Sequel::Model
end

# Table: accounts
# Columns:
#  id    | bigint | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  email | citext | NOT NULL
# Indexes:
#  accounts_pkey        | PRIMARY KEY btree (id)
#  accounts_email_index | UNIQUE btree (email)
# Check constraints:
#  valid_email | (email ~ '^[^,;@ \r\n]+@[^,@; \r\n]+\.[^,@; \r\n]+$'::citext)
# Referenced By:
#  account_authentication_audit_logs | account_authentication_audit_logs_account_id_fkey | (account_id) REFERENCES accounts(id)
#  account_password_reset_keys       | account_password_reset_keys_id_fkey               | (id) REFERENCES accounts(id)
#  account_jwt_refresh_keys          | account_jwt_refresh_keys_account_id_fkey          | (account_id) REFERENCES accounts(id)
#  account_login_failures            | account_login_failures_id_fkey                    | (id) REFERENCES accounts(id)
#  account_lockouts                  | account_lockouts_id_fkey                          | (id) REFERENCES accounts(id)
#  account_session_keys              | account_session_keys_id_fkey                      | (id) REFERENCES accounts(id)
#  account_active_session_keys       | account_active_session_keys_account_id_fkey       | (account_id) REFERENCES accounts(id)
#  account_password_hashes           | account_password_hashes_id_fkey                   | (id) REFERENCES accounts(id)
